# Generated by Django 6.0.5 on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crear_grupos_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='codigo_creado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totem',
            name='codigo_vinculacion',
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name='totem',
            name='vinculado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='totem',
            name='espacio',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='totems',
                to='api.espacio',
            ),
        ),
        migrations.AlterField(
            model_name='totem',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
