# Generated by Django 6.0.5 on 2026-07-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_totem_codigo_vinculacion_vinculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: K1, K2, Única', max_length=50)),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['plan_materia', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='actividad_extra',
        ),
        migrations.AlterUniqueTogether(
            name='carreramateria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='carreramateria',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='carreramateria',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='suspension',
            name='horario_cursado',
        ),
        migrations.AlterModelOptions(
            name='horariocursado',
            options={'ordering': ['comision', 'dia_semana', 'hora_inicio'], 'verbose_name': 'Horario de cursado', 'verbose_name_plural': 'Horarios de cursado'},
        ),
        migrations.AlterModelOptions(
            name='mesaexamen',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Mesa de examen', 'verbose_name_plural': 'Mesas de exámen'},
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='horariocursado',
            name='fecha_fin_vigencia',
        ),
        migrations.RemoveField(
            model_name='horariocursado',
            name='fecha_inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='horariocursado',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='mesaexamen',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='mesaexamen',
            name='llamado',
        ),
        migrations.RemoveField(
            model_name='mesaexamen',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='mesaexamen',
            name='tribunal',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='activo',
        ),
        migrations.AddField(
            model_name='espacio',
            name='tipo_otro',
            field=models.CharField(blank=True, default='', help_text='Completar solo si el tipo es "Otro".', max_length=100),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='fecha',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='piso',
            field=models.CharField(choices=[('planta_baja', 'Planta Baja'), ('primer_piso', 'Primer Piso'), ('segundo_piso', 'Segundo Piso')], default='planta_baja', max_length=20),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='tipo',
            field=models.CharField(choices=[('aula', 'Aula'), ('laboratorio_informatico', 'Laboratorio Informático'), ('secretaria', 'Secretaría'), ('departamento', 'Departamento'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mesaexamen',
            name='turno',
            field=models.CharField(choices=[('febrero', 'Febrero'), ('marzo', 'Marzo'), ('abril', 'Abril'), ('junio', 'Junio'), ('agosto', 'Agosto'), ('septiembre', 'Septiembre'), ('octubre', 'Octubre'), ('diciembre', 'Diciembre')], default='febrero', max_length=15),
        ),
        migrations.AlterField(
            model_name='horariocursado',
            name='comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.comision'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('taller', 'Taller'), ('curso', 'Curso'), ('evento', 'Evento'), ('charla', 'Charla'), ('otro', 'Otro')], max_length=50)),
                ('tipo_otro', models.CharField(blank=True, default='', help_text='Completar solo si el tipo es "Otro".', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='api.espacio')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('paro', 'Paro'), ('inasistencia', 'Inasistencia'), ('feriado', 'Feriado'), ('otro', 'Otro')], max_length=50)),
                ('tipo_otro', models.CharField(blank=True, default='', help_text='Completar solo si el tipo es "Otro".', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('horario_cursado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='api.horariocursado')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='api.evento')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primero', 'Primer año'), ('segundo', 'Segundo año'), ('tercero', 'Tercer año'), ('cuarto', 'Cuarto año'), ('quinto', 'Quinto año')], default='primero', max_length=10)),
                ('modalidad', models.CharField(choices=[('anual', 'Anual'), ('cuatrimestral', 'Cuatrimestral')], default='cuatrimestral', max_length=15)),
                ('cuatrimestre', models.CharField(blank=True, choices=[('primero', 'Primero'), ('segundo', 'Segundo')], help_text='Completar solo si la modalidad es Cuatrimestral.', max_length=10, null=True)),
                ('plan_estudio', models.CharField(choices=[('2023', 'Plan 2023'), ('2008', 'Plan 2008')], default='2023', max_length=4)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='api.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='api.materia')),
            ],
            options={
                'verbose_name': 'Plan - Materia',
                'verbose_name_plural': 'Plan - Materias',
                'ordering': ['carrera', 'nivel', 'cuatrimestre'],
                'unique_together': {('carrera', 'materia', 'nivel', 'plan_estudio')},
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='plan_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='api.planmateria'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='plan_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas_examen', to='api.planmateria'),
        ),
        migrations.DeleteModel(
            name='ActividadExtra',
        ),
        migrations.DeleteModel(
            name='CarreraMateria',
        ),
        migrations.DeleteModel(
            name='Suspension',
        ),
        migrations.AlterUniqueTogether(
            name='comision',
            unique_together={('plan_materia', 'nombre')},
        ),
    ]
