# Generated by Django 6.0.5 on 2026-07-26 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modifica_estructura_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text="Código identificador único (ej: 'horarios', 'examenes')", max_length=50, unique=True)),
                ('col_tam_default', models.PositiveIntegerField(default=4, help_text='Cantidad de columnas por defecto (ancho)')),
                ('fila_tam_default', models.PositiveIntegerField(default=2, help_text='Cantidad de filas por defecto (alto)')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='totem',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totems', to='api.plantilla'),
        ),
        migrations.CreateModel(
            name='PlantillaWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_pos', models.PositiveIntegerField(help_text='Ubicación de la columna en la grilla (X, ej: 0, 1, 2, 3)')),
                ('fila_pos', models.PositiveIntegerField(help_text='Ubicación de la fila en la grilla (Y, ej: 0, 1...)')),
                ('col_tam', models.PositiveIntegerField(default=4, help_text='Cantidad de columnas que abarca (ancho)')),
                ('fila_tam', models.PositiveIntegerField(default=2, help_text='Cantidad de filas que abarca (alto)')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets_posiciones', to='api.plantilla')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_posiciones', to='api.widget')),
            ],
            options={
                'verbose_name': 'Widget en Plantilla',
                'verbose_name_plural': 'Widgets en Plantillas',
                'ordering': ['plantilla', 'fila_pos', 'col_pos'],
            },
        ),
    ]
