# Generated by Django 6.0.5 on 2026-07-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_crear_modelos_widgets_y_plantillas'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='enlace',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='noticias',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('scraping', 'Scraping')], default='manual', max_length=10),
        ),
    ]
