# Generated by Django 6.0.5 on 2026-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_noticias_enlace_noticias_imagen_url_noticias_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
