# Generated by Django 6.0.5 on 2026-07-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_renombrar_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
