# Generated by Django 6.0.5 on 2026-08-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_totem_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('taller', 'Taller'), ('curso', 'Curso'), ('recreativo', 'Recreativo'), ('charla', 'Charla'), ('otro', 'Otro')], max_length=50),
        ),
    ]
