# Generated by Django 6.0.5 on 2026-08-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_evento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[('grado', 'Grado'), ('tecnica', 'Tecnicatura'), ('posgrado', 'Posgrado'), ('diplomatura', 'Diplomatura')], default='grado', max_length=15),
        ),
    ]
