# Generated by Django 6.0.5 on 2026-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cargar_widgets_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código abreviado (ej: ISI, IEM, IQ, LAR)', max_length=10, null=True, unique=True),
        ),
    ]
