# Generated by Django 6.0.5 on 2026-08-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cargar_widgets_iniciales'),
        ('api', '0013_populate_carrera_codigo'),
    ]

    operations = [
    ]
