# Generated by Django 6.0.5 on 2026-08-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_carrera_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horariocursado',
            unique_together={('comision', 'espacio', 'dia_semana', 'hora_inicio', 'hora_fin')},
        ),
        migrations.AlterUniqueTogether(
            name='mesaexamen',
            unique_together={('plan_materia', 'espacio', 'fecha', 'hora', 'turno')},
        ),
    ]
