# Generated by Django 6.0.5 on 2026-08-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20260805_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('inicio_cuatrimestre', 'Inicio de Cuatrimestre'), ('fin_cuatrimestre', 'Fin de Cuatrimestre'), ('mesa_examen', 'Mesa de Examen'), ('receso_invernal', 'Receso Invernal'), ('feriado', 'Feriado'), ('otro', 'Otro')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Para eventos de rango. Si es null, es un evento puntual.', null=True)),
                ('todo_el_dia', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', help_text='Color hex opcional para override (ej: #FF5733).', max_length=7)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('documento_fuente', models.FileField(blank=True, help_text='PDF o imagen del calendario oficial.', null=True, upload_to='calendario/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
