# Generated by Django 6.0.5 on 2026-08-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_modifica_horarios_y_mesas'),
        ('api', '0015_eventocalendario'),
    ]

    operations = [
    ]
