# Generated by Django 6.0.5 on 2026-08-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cargar_widget_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariocursado',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.espacio'),
        ),
    ]
