# Generated by Django 6.0.5 on 2026-08-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cargar_widget_noticias'),
        ('api', '0018_alter_horariocursado_espacio'),
    ]

    operations = [
    ]
