# Generated by Django 6.0.5 on 2026-08-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cargar_seed_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_id', models.CharField(help_text='Identificador del polígono en el SVG (ej: "1", "escaleras1", "baño2").', max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('aula', 'Aula'), ('oficina', 'Oficina'), ('departamento', 'Departamento'), ('secretaria', 'Secretaría'), ('laboratorio', 'Laboratorio'), ('servicio', 'Servicio'), ('escaleras', 'Escaleras'), ('ascensor', 'Ascensor'), ('baños', 'Baños'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('piso', models.CharField(choices=[('baja', 'Planta Baja'), ('primero', 'Primer Piso'), ('segundo', 'Segundo Piso')], max_length=10)),
            ],
            options={
                'verbose_name': 'Ubicación en Mapa',
                'verbose_name_plural': 'Ubicaciones en Mapa',
                'ordering': ['piso', 'svg_id'],
                'unique_together': {('svg_id', 'piso')},
            },
        ),
    ]
