# Generated by Django 6.0.5 on 2026-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_seed_ubicaciones_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='pin_mapa_piso',
            field=models.CharField(blank=True, choices=[('baja', 'Planta Baja'), ('primero', 'Primer Piso'), ('segundo', 'Segundo Piso')], help_text='Piso donde está ubicado el tótem en el mapa interactivo.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='totem',
            name='pin_mapa_svg_x',
            field=models.FloatField(blank=True, help_text='Coordenada X en el sistema de coordenadas del SVG del mapa.', null=True),
        ),
        migrations.AddField(
            model_name='totem',
            name='pin_mapa_svg_y',
            field=models.FloatField(blank=True, help_text='Coordenada Y en el sistema de coordenadas del SVG del mapa.', null=True),
        ),
    ]
