# Generated by Django 6.0.5 on 2026-09-03 21:48

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_totem_pin_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_archivo', models.FileField(blank=True, help_text='Video MP4 vertical para pantalla del tótem.', null=True, upload_to='totems/videos/', validators=[api.validators.validar_video])),
                ('intervalo', models.IntegerField(default=60, help_text='Segundos de inactividad antes de mostrar el video.')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de Video',
                'verbose_name_plural': 'Configuraciones de Video',
            },
        ),
    ]
