# Generated by Django 6.0.5 on 2026-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_evento_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmateria',
            name='plan_estudio',
            field=models.CharField(choices=[('2023', 'Plan 2023'), ('2008', 'Plan 2008'), ('1995', 'Plan 1995')], default='2023', max_length=4),
        ),
    ]
