# Generated by Django 6.0.5 on 2026-09-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_planmateria_plan_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmateria',
            name='plan_estudio',
            field=models.CharField(choices=[('2026', 'Plan 2026'), ('2023', 'Plan 2023'), ('2010', 'Plan 2010'), ('2008', 'Plan 2008'), ('2001', 'Plan 2001'), ('1995', 'Plan 1995')], default='2023', max_length=4),
        ),
    ]
