# Generated by Django 6.0.5 on 2026-09-06 16:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_configuracionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='video_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='totem',
            name='video_archivo',
            field=models.FileField(blank=True, help_text='Video MP4 vertical para pantalla del tótem.', null=True, upload_to='totems/videos/', validators=[api.validators.validar_video]),
        ),
        migrations.AddField(
            model_name='totem',
            name='video_intervalo',
            field=models.IntegerField(default=60, help_text='Segundos de inactividad antes de mostrar el video.'),
        ),
    ]
