# Generated by Django 6.0.5 on 2026-09-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_migrate_video_to_totems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionVideo',
        ),
    ]
