# Generated by Django 6.0.5 on 2026-09-07 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_configuracionvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='video_intervalo',
            field=models.IntegerField(default=60, help_text='Segundos de inactividad antes de mostrar el video.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
