# Generated by Django 6.0.5 on 2026-09-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_cargar_datos_seed_completos'),
        ('api', '0028_remove_configuracionvideo'),
    ]

    operations = [
    ]
