# Generated by Django 6.0.5 on 2026-09-08 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_video_intervalo_validators'),
        ('api', '0029_merge_20260907_2315'),
    ]

    operations = [
    ]
