# Generated by Django 6.0.5 on 2026-09-25 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_cargar_widget_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='totem',
            name='video_intervalo',
            field=models.IntegerField(default=60, help_text='Segundos de inactividad antes de mostrar el video.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
