# Generated by Django 6.0.5 on 2026-09-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_evento_destacado_alter_totem_video_intervalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='espacio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
