# Generated by Django 6.0.5 on 2026-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_evento_espacio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacio',
            options={'ordering': ['edificio', 'piso', 'nombre'], 'verbose_name': 'Espacio', 'verbose_name_plural': 'Espacios'},
        ),
        migrations.AddField(
            model_name='espacio',
            name='edificio',
            field=models.CharField(choices=[('central', 'Edificio Central'), ('anexo', 'Anexo')], default='central', max_length=20),
        ),
    ]
