# Generated by Django 6.0.5 on 2026-09-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_poblar_edificios_anexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planmateria',
            options={'ordering': ['carrera', 'nivel'], 'verbose_name': 'Plan - Materia', 'verbose_name_plural': 'Plan - Materias'},
        ),
        migrations.RemoveField(
            model_name='planmateria',
            name='cuatrimestre',
        ),
        migrations.RemoveField(
            model_name='planmateria',
            name='modalidad',
        ),
    ]
